version: '3.8'

services:
  api:
    build: .
    container_name: portfolio-api
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=sua_senha
      - JWT_SECRET=seu_jwttoken         //não é necessário
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: portfolio-db
    environment:
      - POSTGRES_DB=projeto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sua_senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: